services:
  nextcloud:
    image: nextcloud:latest
    container_name: chome_nextcloud
    restart: unless-stopped
    networks: [chome-net]
    dns:
      - 192.168.1.10
    ports:
      - '28080:80'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - /mnt/data/projects/chome/volumes/nextcloud:/var/www/html
      - /mnt/data/storage:/media/storage:rw
      - /mnt/nas/media:/media/nas:rw
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.chome.pro odin:28080
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_HOST=chome_postgres
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    extra_hosts:
      - 'cloud.chome.pro:172.17.0.1'
