services:
  npm:
    image: 'jlesage/nginx-proxy-manager:latest'
    container_name: chome_npm
    restart: unless-stopped
    ports:
      - '80:8080'
      - '443:4443'
      - '81:8181'
    networks:
      - chome-net
      - core-net
    dns:
      - 192.168.1.10
    volumes:
      - npm:/config:rw
      # - npm_data:/data:rw
      # - npm_letsencrypt:/etc/letsencrypt:rw

volumes:
  npm:
