services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: chome_prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /mnt/data/projects/chome/volumes/prowlarr:/config
    ports:
      - 29696:9696
